### ISSUE TITLE
Add Navigation Bar to the HomePage.dart

### ISSUE THREAD

**Issue by shivlendra20** [mohitsoni-dev/medicine_reminder#12]
1. Adding navigation bar at the bottom.
2. It includes items such as Schedule, Medication, FloatingActionButton, Settings, and File Icon widgets.
3. Currently every Item will show some sort of message to the user on the homepage itself whenever the User taps on a particular one.
4. By tapping FloatingActionButton, It'll navigate to the PatientForm.dart as usual.

![Screenshot_2021-05-16-00-30-33-35_79cd4e626f662bece259227a91b18e1b 1](https://user-images.githubusercontent.com/77846233/118384052-ced1d980-b620-11eb-9651-9354e1af52b6.jpg)

**Comment by mohitsoni-dev** [comment]
@shivlendra20 you can start working on this. Make sure your fork is up to date to avoid any conflict.

**Comment by shivlendra20** [comment]
> 
> 
> @shivlendra20 you can start working on this. Make sure your fork is up to date to avoid any conflict.

Ok got it..thanks

**Comment by shivlendra20** [comment]
> 
> 
> @shivlendra20 you can start working on this. Make sure your fork is up to date to avoid any conflict.

Ok got it thanks @mohitsoni-dev

**Comment by mohitsoni-dev** [comment]
Great. Make a pull request I'll clone your branch and review it.
