### ISSUE TITLE
Empty Drawer Class !?

### ISSUE THREAD

**Issue by Yakksh** [mohitsoni-dev/medicine_reminder#6]
![Screenshot 2021-05-14 155929](https://user-images.githubusercontent.com/59383086/118258397-6cb48f80-b4cd-11eb-862a-3a76344d1995.jpg)

**Comment by mohitsoni-dev** [comment]
Hi @Yakksh, DrawerClass is not actually empty. It is displaying all patients from the database which is empty. Try filling dummy data through form and you will see that added patients are appearing in the Drawer.

Do not remove the existing DrawerClass, improve its UI.
